### ISSUE TITLE
EPIC: Migrate k6 discourse to grafana forum

### ISSUE THREAD

**Issue by mellieA** [grafana/grafana-community-support-squad#57]
Summary: k6 has their own discourse forum which we will merge into the existing grafana community forum

This issue is a starting point to assign and track the tasks and questions that we encounter as we research what's involved from the community squads and discourse. 

More context in https://github.com/grafana/k6-internal-docs/issues/272 
Our tentative completion date is the end of Q1

- [ ] Find out if discourse has tools to migrate the forum
- [ ] What content can be migrated? 
- [ ] What happens to the old forum, is there a redirect? 
- [ ] How are logins handled for k6 users

**Comment by immavalls** [comment]
I'm starting to document the requirements, planning, etc in https://docs.google.com/document/d/1Wo27t2fzyc7oQ2TCs5n8vhMBIgDhl4Vl1-OSXNzHtuw/, for internal discussions before we proceed. To update also once we kick off the project with Discourse's migration team.
